/* Generated By:JavaCC: Do not edit this line. JsltParserTreeConstants.java Version 4.1d1 */
package com.schibsted.spt.data.jslt.parser;

public interface JsltParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTMODULE = 1;
  public int JJTEXPRLIST = 2;
  public int JJTEXPR = 3;
  public int JJTANDEXPR = 4;
  public int JJTCOMPARATIVEEXPR = 5;
  public int JJTCOMPARATOR = 6;
  public int JJTADDITIVEEXPR = 7;
  public int JJTADDITIVEOPERATOR = 8;
  public int JJTMULTIPLICATIVEEXPR = 9;
  public int JJTMULTIPLICATIVEOPERATOR = 10;
  public int JJTBASEEXPR = 11;
  public int JJTCHAINABLE = 12;
  public int JJTCHAINLINK = 13;
  public int JJTPARENTHESIS = 14;
  public int JJTDOTKEY = 15;
  public int JJTARRAYSLICING = 16;
  public int JJTCOLON = 17;
  public int JJTVOID = 18;
  public int JJTARRAY = 19;
  public int JJTOBJECT = 20;
  public int JJTMATCHER = 21;
  public int JJTMATCHERMINUS = 22;
  public int JJTPAIR = 23;
  public int JJTOBJECTCOMPREHENSION = 24;
  public int JJTIFSTATEMENT = 25;
  public int JJTELSEBRANCH = 26;
  public int JJTFORSTATEMENT = 27;
  public int JJTFUNCTIONCALL = 28;
  public int JJTLET = 29;
  public int JJTFUNCTIONDECL = 30;
  public int JJTIMPORT = 31;


  public String[] jjtNodeName = {
    "Start",
    "Module",
    "ExprList",
    "Expr",
    "AndExpr",
    "ComparativeExpr",
    "Comparator",
    "AdditiveExpr",
    "AdditiveOperator",
    "MultiplicativeExpr",
    "MultiplicativeOperator",
    "BaseExpr",
    "Chainable",
    "ChainLink",
    "Parenthesis",
    "DotKey",
    "ArraySlicing",
    "Colon",
    "void",
    "Array",
    "Object",
    "Matcher",
    "MatcherMinus",
    "Pair",
    "ObjectComprehension",
    "IfStatement",
    "ElseBranch",
    "ForStatement",
    "FunctionCall",
    "Let",
    "FunctionDecl",
    "Import",
  };
}
/* JavaCC - OriginalChecksum=f3be26f816afcbcc51b0a996b0ab7708 (do not edit this line) */
